codebros3_0/urls.py
from django.conf.urls import include, url
from django.contrib import admin

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'', include('review_it.urls')),
]

review_it/urls.py
from django.conf.urls import url
from . import views

app_name = 'review_it'

urlpatterns = [
    url(r'^$', views.home , name = 'home'),
    url(r'^logout/$', views.logout_ , name = 'logout'),
    url(r'^login_page/$' , views.login_page , name = 'login_page'),
    url(r'^login_auth/$', views.login_auth , name='login_auth'),
    url(r'^signup/$' , views.signup , name = 'signup'),
    url(r'^add_user/$' , views.add_user , name = 'add_user'),
    url(r'^write_review/$' , views.write_review , name = 'write_review'),
    url(r'^add_review/$' , views.add_review , name = 'add_review'),
    url(r'^search/$' , views.search , name = 'search'),
]

review_it/models.py
from django.db import models
from django.contrib.auth.models import User
from django.utils import timezone

class Book(models.Model):
    title=models.CharField(max_length=100)
    auther=models.CharField(max_length=30 ,blank=True, null=True)
    publisher = models.CharField(max_length=30,blank=True , null=True)
    number_of_reviews = models.IntegerField(default=0)
    average_rating = models.FloatField(default=0)
    def __str__(self):
        return self.title

class Review(models.Model):
    review=models.CharField(max_length=2000)
    star_rating = models.IntegerField(default=0)
    book=models.CharField(max_length=50 , null=True)
    review_by=models.OneToOneField(User , null=True)
    datetime = models.DateTimeField(default=timezone.now)

review_it/views.py
from django.shortcuts import render
from django.contrib.auth import authenticate, login , logout
from django.db import models
from django.core.paginator import Paginator, EmptyPage, PageNotAnInteger
from django.contrib.auth.models import User
from .models import Book,Review
from django.contrib.auth.decorators import login_required

def home(request):
    return render(request , 'home.html')

def logout_(request):
    logout(request)
    return render(request , 'home.html')

def login_page(request):
    return render(request,'login.html')

def login_auth(request):
    username = request.POST['username']
    password = request.POST['password']
    user = authenticate(username=username, password=password)
    if user is not None:
        login(request , user)
        return render(request , 'login_home.html')
    else:
        return render(request , 'login_fail.html')

def signup(request):
    return render(request , 'signup.html')

def add_user(request):
    """ new_user = User()
    new_user.username = request.POST['username']
    new_user.password = request.POST['password']
    new_user.first_name = request.POST['first_name']
    new_user.last_name = request.POST['last_name']
    new_user.email = request.POST['email']
    new_user.save()"""
    user = User.objects.create_user(request.POST['username'],email=request.POST['email'],password=request.POST['password'])
    return render(request , 'user_added.html')

@login_required(login_url='{% review_it:login_page %}')
def write_review(request):
    return render(request , 'write_review.html')


def add_review(request):
    """new_book = Book()
    new_book.title=request.POST['title']
    new_book.auther=request.POST['author']
    new_book.publisher=request.POST['publisher']
    new_book.number_of_reviews = 1
    new_book.average_rating = request.POST['star_rating']
    new_book.save()"""
    new_review=Review()
    new_review.review = request.POST['review']
    new_review.star_rating = request.POST['star_rating']
    new_review.review_by = User.objects.get(id=request.user.id)
    new_review.book= request.POST['title']
    #check_book = Book.objects.filter(title=new_book.title)
    #if check_book==[]:
    #a=check_book[0]
   # new_review.book = request.POST['title']
    #else:
     #   check_book[0].number_of_reviews += 1
      #  check_book[0].average_rating = 3
        #check_book[0].average_rating = (((check_book[0].average_rating)* (int(check_book[0].number_of_reviews)-1))+(new_review.star_rating))/(check_book[0].number_of_reviews)
       # check_book[0].save()
        #new_review.review_of = Book.objects.get(id=check_book[0].id)
    new_review.save()
    return render(request , 'login_home.html')

def search(request):
    svalue = request.POST['svalue']
    all_reviews=Review.objects.filter(book=svalue).order_by('-datetime')
    avg=0
    for review in all_reviews:
        avg+=review.star_rating
    avg_rating=round(avg/len(all_reviews),2)
    return render(request , 'results.html' , {'all_reviews':all_reviews, 'avg_rating': avg_rating , 'title':svalue})

review_it/templates/base.html
{% load staticfiles %}

    <!DOCTYPE html>
    <html lang="en">

    <head>
        {% block feature %}
        {% endblock %}
        <meta charset="utf-8">
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
        <title>Review_It</title>
        <link href='https://fonts.googleapis.com/css?family=Merriweather:400,700|Merriweather+Sans' rel='stylesheet' type='text/css'>
        <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/css/bootstrap.min.css">
        <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/font-awesome/4.6.3/css/font-awesome.min.css">
        <link href="{% static 'css/bootstrap.min.css' %}" rel="stylesheet">
        <link href="{% static 'css/sidebar-menu.css' %}" rel="stylesheet">
        <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
        <script type="text/javascript" src="//ajax.googleapis.com/ajax/libs/jquery/2.1.1/jquery.min.js"></script>
        <script type="text/javascript" src="{% static 'ckeditor.js' %}"></script>
        <script type="text/javascript" src="{% static 'ckeditor-init.js' %}"></script>

        <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">
    </head>

    {% block content %}
    {% endblock %}
    </html>

review_it/templates/home.html
{% extends 'base.html' %}

{% block content %}
<body>

    <nav class="navbar navbar-default">
    <div class="container-fluid">
    <div class="col-md-4">
     <div class="navbar-header">
       <a class="avbar-brand" href="#">
         <img alt="Brand" src="https://www.freelogoservices.com/api/main/images/1j+ojl1FOMkX9WypfBe43D6kj...GJqBBKkRbJwXs1M3EMoAJtlCcohfps...fw+" style="padding-top:-20px;height:65px;">
       </a>
     </div></div>
    <div class="col-md-4">

    <form class="navbar-form navbar-left" action="{% url 'review_it:search' %}" method="POST">
    {% csrf_token %}
        <div class="form-group">
          <input type="text" class="form-control" placeholder="Search" name="svalue">
        </div>
        <button type="submit" class="btn btn-default">Submit</button>
      </form>

    </div>
    <div class="col-md-2"></div>
    <div class="col-md-1"><a href="{% url 'review_it:login_page' %}" type="button" class="btn btn-default navbar-btn" style="margin-left:1em;">Sign In</a>
    </div>
    <div class="col-md-1"><a href="{% url 'review_it:signup' %}" type="button" class="btn btn-default navbar-btn" style="margin-left:1em;">Sign Up</a></div>
    </div>
    </nav>




<div class="row">
<div class="col-md-3"><p></p></div>
<div class="col-md-6">
<h1 style="padding-left:6em;">Sign Up</h1>
<form action="{% url 'review_it:add_user' %}">
{% csrf_token %}
  <div class="form-group">
    <label for="First Name">First Name</label>
    <input type="text" class="form-control" id="fname" name="fname" placeholder="First Name" name="first_name">
  </div>
  <div class="form-group">
    <label for="Last Name">Last Name</label>
    <input type="text" class="form-control" id="lname" name="lname" placeholder="Last Name" name="last_name">
  </div>
  <div class="form-group">
    <label for="Username">Username</label>
    <input type="text" class="form-control" id="uname" name="uname" placeholder="Username" name="username">
  </div>
  <div class="form-group">
    <label for="Password">Password</label>
    <input type="password" class="form-control" id="pswd" name="pswd" placeholder="Password" name="password">
  </div>
  <div class="form-group">
    <label for="formGroupExampleInput2">Email</label>
    <input type="email" class="form-control" id="email" name="email" placeholder="Email" name="email">
  </div>
  <div class="pull-right"><button type="submit" class="btn btn-primary">Sign Up!</button></div>

</form>
</div>
</div>








<script type="text/javascript" src="https://code.jquery.com/jquery-2.1.1.min.js"></script>
        <script type="text/javascript" src="js/materialize.min.js"></script>

        <!-- Slider Javascript -->
        <script src='http://cdnjs.cloudflare.com/ajax/libs/jquery/2.1.3/jquery.min.js'></script>
        <script src="js/slider.js" type="text/javascript"></script>
</body>

{% endblock %}

review_it/templates/login.html
{% extends 'base.html' %}
{% block content %}

<body>

  <nav class="navbar navbar-default">
    <div class="container-fluid">
    <div class="col-md-4">
     <div class="navbar-header">
       <a class="avbar-brand" href="#">
         <img alt="Brand" src="https://www.freelogoservices.com/api/main/images/1j+ojl1FOMkX9WypfBe43D6kj...GJqBBKkRbJwXs1M3EMoAJtlCcohfps...fw+" style="padding-top:-20px;height:65px;">
       </a>
     </div></div>
    <div class="col-md-4">

    <form class="navbar-form navbar-left" action="{% url 'review_it:search' %}" method="POST">
    {% csrf_token %}
        <div class="form-group">
          <input type="text" class="form-control" placeholder="Search" name="svalue">
        </div>
        <button type="submit" class="btn btn-default">Submit</button>
      </form>

    </div>
    <div class="col-md-2"></div>
    <div class="col-md-1"><a href="{% url 'review_it:signup' %}" type="button" class="btn btn-default navbar-btn" style="margin-left:1em;">Sign Up</a>
    </div>
    <div class="col-md-1"><a href="{% url 'review_it:home' %}" type="button" class="btn btn-default navbar-btn" style="margin-left:1em;">Home</a></div>
    </div>
    </nav>




<div class="row">
<div class="col-md-3"><p></p></div>
<div class="col-md-6">
<h1 style="padding-left:6em;">Sign In</h1>
<form action="{% url 'review_it:login_auth'  %}" method="POST">
{% csrf_token %}
    <div class="form-group">
    <label for="Username">Username</label>
    <input type="text" class="form-control" id="uname" placeholder="Username" name="username">
  </div>
  <div class="form-group">
    <label for="Password">Password</label>
    <input type="password" class="form-control" id="pswd" placeholder="Password" name="password">
  </div>
    <div class="pull-right"><button type="submit" class="btn btn-primary">Sign In</button></div>

</form>
</div>

</div>








<script type="text/javascript" src="https://code.jquery.com/jquery-2.1.1.min.js"></script>
        <script type="text/javascript" src="js/materialize.min.js"></script>

        <!-- Slider Javascript -->
        <script src='http://cdnjs.cloudflare.com/ajax/libs/jquery/2.1.3/jquery.min.js'></script>
        <script src="js/slider.js" type="text/javascript"></script>
</body>
{%  endblock %}

review_it/templates/login_fail.html
{% extends 'base.html' %}
{% block content %}

<body>

  <nav class="navbar navbar-default">
    <div class="container-fluid">
    <div class="col-md-4">
     <div class="navbar-header">
       <a class="avbar-brand" href="#">
         <img alt="Brand" src="1jojl1FOMkX9WypfBe43D6kj...GJrxVMmh7JwXs1M3EMoAJtlCcohfFj8f46" style="padding-top:-20px;height:65px;">
       </a>
     </div></div>
    <div class="col-md-4">

    <form class="navbar-form navbar-left" >
        <div class="form-group">
          <input type="text" class="form-control" placeholder="Search" name="svalue">
        </div>
        <button type="submit" class="btn btn-default">Submit</button>
      </form>

    </div>
    <div class="col-md-2"></div>
    <div class="col-md-1"><a href="{% url 'review_it:signup' %}" type="button" class="btn btn-default navbar-btn" style="margin-left:1em;">Sign Up</a>
    </div>
    <div class="col-md-1"><a href="{% url 'review_it:home' %}" type="button" class="btn btn-default navbar-btn" style="margin-left:1em;">Home</a></div>
    </div>
    </nav>




<div class="row">
<div class="col-md-3"><p></p></div>
<div class="col-md-6">
<h1 style="padding-left:6em;">Sign In</h1>
<form action="{% url 'review_it:login_auth'  %}" method="POST">
{% csrf_token %}
    <div class="form-group">
    <label for="Username">Username</label>
    <input type="text" class="form-control" id="uname" placeholder="Username" name="username">
  </div>
  <div class="form-group">
    <label for="Password">Password</label>
    <input type="password" class="form-control" id="pswd" placeholder="Password" name="password">
  </div>
    <div class="pull-right"><button type="submit" class="btn btn-primary">Sign In</button></div>

</form>
</div>

</div>
<div class="container"><p style="color:red;text-align:center;"><strong>Invalid Username or Password</strong></p></div>








<script type="text/javascript" src="https://code.jquery.com/jquery-2.1.1.min.js"></script>
        <script type="text/javascript" src="js/materialize.min.js"></script>

        <!-- Slider Javascript -->
        <script src='http://cdnjs.cloudflare.com/ajax/libs/jquery/2.1.3/jquery.min.js'></script>
        <script src="js/slider.js" type="text/javascript"></script>
</body>
{%  endblock %}

review_it/templates/login_home.html
{% extends 'base.html' %}

{% block content %}
    <body>

<nav class="navbar navbar-default">
    <div class="container-fluid">
    <div class="col-md-4">
     <div class="navbar-header">
       <a class="avbar-brand" href="#">
         <img alt="Brand" src="https://www.freelogoservices.com/api/main/images/1j+ojl1FOMkX9WypfBe43D6kj...GJqBBKkRbJwXs1M3EMoAJtlCcohfps...fw+" style="padding-top:-20px;height:65px;">
       </a>
     </div></div>
    <div class="col-md-6">

    <form class="navbar-form navbar-left" action="{% url 'review_it:search' %}" method="POST">
    {% csrf_token %}
        <div class="form-group">
          <input type="text" class="form-control" placeholder="Search" name="svalue">
        </div>
        <button type="submit" class="btn btn-default">Submit</button>
      </form>

    </div>
    <div class="col-md-2"><a href="{% url 'review_it:logout' %}" type="button" class="btn btn-default navbar-btn" style="margin-left:1em;">Sign Out</a></div>
    </div>
    </nav>




<div class="row">
<div class="col-md-2"><p></p></div>
<div class="col-md-8">
<h1 style="padding-left:8em;">Write Review</h1>
<form action="{% url 'review_it:add_review' %}" method="POST">
{% csrf_token %}
    <div class="row">
    <div class="col-md-6">
    <div class="form-group required">
    <label for="Title">Book/Movie Title</label>
    <input type="text" name="title" class="form-control" id="title" placeholder="Title" required="True">
    </div></div>
    <div class="col-md-6">
    <div class="form-group required">
    <label for="Author">Author</label>
    <input type="text" class="form-control" name="author" id="author" placeholder="Author" required="True">
    </div></div></div>
    <div class="row">
    <div class="col-md-6">
    <div class="form-group required">
    <label for="Publisher">Publisher</label>
    <input type="text" class="form-control" id="publisher" name="publisher" placeholder="Publisher" >
    </div></div>
    <div class="col-md-6">
    <div class="form-group">
    <label for="Rating">Rating</label><br>
    <label class="radio-inline">
     <input id="one" name="star_rating" value="1" type="radio" >
     1</label>
    <label class="radio-inline">
     <input id="two" name="star_rating" value="2" type="radio" >
     2</label>
    <label class="radio-inline">
     <input id="three" name="star_rating" value="3" type="radio">
     3</label>
    <label class="radio-inline">
     <input id="four" name="star_rating" value="4" type="radio">
     4</label>
    <label class="radio-inline">
     <input id="five" name="star_rating" value="5" type="radio">
     5</label>
    </div>
    </div></div>
    <div class="form-group required">
    <label for="Publisher">Review</label>
    <textarea type="text" class="form-control" id="review" name="review" placeholder="It's a.." rows="8" style="overflow:auto;"></textarea>
    </div>
    <div class="pull-right"><button type="submit" class="btn btn-primary">Submit</button></div>

</form>
</div>
</div>








<script type="text/javascript" src="https://code.jquery.com/jquery-2.1.1.min.js"></script>
        <script type="text/javascript" src="js/materialize.min.js"></script>

        <!-- Slider Javascript -->
        <script src='http://cdnjs.cloudflare.com/ajax/libs/jquery/2.1.3/jquery.min.js'></script>
        <script src="js/slider.js" type="text/javascript"></script>
</body>
{% endblock %}

review_it/templates/results.html
{% extends 'base.html' %}

{% block content %}
<body>

    <nav class="navbar navbar-default">
    <div class="container-fluid">
    <div class="col-md-4">
     <div class="navbar-header">
       <a class="avbar-brand" href="#">
         <img alt="Brand" src="https://www.freelogoservices.com/api/main/images/1j+ojl1FOMkX9WypfBe43D6kj...GJqBBKkRbJwXs1M3EMoAJtlCcohfps...fw+" style="padding-top:-20px;height:65px;">
       </a>
     </div></div>
    <div class="col-md-4">

    <form class="navbar-form navbar-left" action="{% url 'review_it:search' %}" method="POST">
    {% csrf_token %}
        <div class="form-group">
          <input type="text" class="form-control" placeholder="Search" name="svalue">
        </div>
        <button type="submit" class="btn btn-default">Submit</button>
      </form>

    </div>
    <div class="col-md-2"></div>
    <div class="col-md-1"><a href="{% url 'review_it:login_page' %}" type="button" class="btn btn-default navbar-btn" style="margin-left:1em;">Sign In</a>
    </div>
    <div class="col-md-1"><a href="{% url 'review_it:signup' %}" type="button" class="btn btn-default navbar-btn" style="margin-left:1em;">Sign Up</a></div>
    </div>
    </nav>




<div class="container">
  <div class="jumbotron">
    <h1 style="color:black;"> <b>{{ title }}   </b><small style="color:#043A8D;font-size:40%">Average Rating  - {{ avg_rating }} / 5</small></h1>
    <hr>
    {% for review in all_reviews %}
      <div><h4 style="color:black;"><strong>{{ review.book }} - <span style="color:#043A8D">{{ review.review_by }}</span> <span class="pull-right">{{ review.datetime }}</span></strong></h4></div>
      <p style="color:blue;font-size:small">Rating {{ review.star_rating }}/5</p>
      <p>{{ review.review }}</p>
      <hr>
    {% endfor %}
  </div>

</div>








<script type="text/javascript" src="https://code.jquery.com/jquery-2.1.1.min.js"></script>
        <script type="text/javascript" src="js/materialize.min.js"></script>

        <!-- Slider Javascript -->
        <script src='http://cdnjs.cloudflare.com/ajax/libs/jquery/2.1.3/jquery.min.js'></script>
        <script src="js/slider.js" type="text/javascript"></script>
</body>

{% endblock %}

review_it/templates/signup.html
{% extends 'base.html' %}

{% block content %}
<body>

    <nav class="navbar navbar-default">
    <div class="container-fluid">
    <div class="col-md-4">
     <div class="navbar-header">
       <a class="avbar-brand" href="#">
         <img alt="Brand" src="https://www.freelogoservices.com/api/main/images/1j+ojl1FOMkX9WypfBe43D6kj...GJqBBKkRbJwXs1M3EMoAJtlCcohfps...fw+" style="padding-top:-20px;height:65px;">
       </a>
     </div></div>
    <div class="col-md-4">

    <form class="navbar-form navbar-left"  action="{% url 'review_it:search' %}" method="POST">
    {% csrf_token %}
        <div class="form-group">
          <input type="text" class="form-control" placeholder="Search" name="svalue">
        </div>
        <button type="submit" class="btn btn-default">Submit</button>
      </form>

    </div>

    <div class="col-md-2"></div>
    <div class="col-md-1"><a href="{% url 'review_it:login_page' %}" type="button" class="btn btn-default navbar-btn" style="margin-left:1em;">Sign In</a>
    </div>
    <div class="col-md-1"><a href="{% url 'review_it:home' %}" type="button" class="btn btn-default navbar-btn" style="margin-left:1em;">Home</a></div>
    </div>
    </nav>




<div class="row">
<div class="col-md-3"><p></p></div>
<div class="col-md-6">
<h1 style="padding-left:6em;">Sign Up</h1>
<form action="{% url 'review_it:add_user' %}" method="POST">
{% csrf_token %}
  <div class="form-group">
    <label for="First Name">First Name</label>
    <input type="text" class="form-control" id="fname" placeholder="First Name" name="first_name">
  </div>
  <div class="form-group">
    <label for="Last Name">Last Name</label>
    <input type="text" class="form-control" id="lname" placeholder="Last Name" name="last_name">
  </div>
  <div class="form-group">
    <label for="Username">Username</label>
    <input type="text" class="form-control" id="uname" placeholder="Username" name="username">
  </div>
  <div class="form-group">
    <label for="Password">Password</label>
    <input type="password" class="form-control" id="pswd" placeholder="Password" name="password">
  </div>
  <div class="form-group">
    <label for="formGroupExampleInput2">Email</label>
    <input type="email" class="form-control" id="email" placeholder="Email" name="email">
  </div>
  <div class="pull-right"><button type="submit" class="btn btn-primary">Sign Up!</button></div>

</form>
</div>
</div>








<script type="text/javascript" src="https://code.jquery.com/jquery-2.1.1.min.js"></script>
        <script type="text/javascript" src="js/materialize.min.js"></script>

        <!-- Slider Javascript --->
        <script src='http://cdnjs.cloudflare.com/ajax/libs/jquery/2.1.3/jquery.min.js'></script>
        <script src="js/slider.js" type="text/javascript"></script>
</body>

{% endblock %}

review_it/templates/user_added.html
{% extends 'base.html' %}
{% block content %}

<body>

  <nav class="navbar navbar-default">
    <div class="container-fluid">
    <div class="col-md-4">
     <div class="navbar-header">
       <a class="avbar-brand" href="#">
         <img alt="Brand" src="1jojl1FOMkX9WypfBe43D6kj...GJrxVMmh7JwXs1M3EMoAJtlCcohfFj8f46" style="padding-top:-20px;height:65px;">
       </a>
     </div></div>
    <div class="col-md-4">

    <form class="navbar-form navbar-left" >
        <div class="form-group">
          <input type="text" class="form-control" placeholder="Search" name="svalue">
        </div>
        <button type="submit" class="btn btn-default">Submit</button>
      </form>

    </div>
    <div class="col-md-2"></div>
    <div class="col-md-1"><a href="{% url 'review_it:signup' %}" type="button" class="btn btn-default navbar-btn" style="margin-left:1em;">Sign Up</a>
    </div>
    <div class="col-md-1"><a href="{% url 'review_it:home' %}" type="button" class="btn btn-default navbar-btn" style="margin-left:1em;">Home</a></div>
    </div>
    </nav>




<div class="row">
<div class="col-md-3"><p></p></div>
<div class="col-md-6">
<div class="container">
  <p style="color:blue;text-align:center;"><strong>CONGRATULATIONS! Account created successfully<br>Login to continue</strong></p>
</div>

<h1 style="padding-left:6em;">Sign In</h1>
<form action="{% url 'review_it:login_auth'  %}" method="POST">
{% csrf_token %}
    <div class="form-group">
    <label for="Username">Username</label>
    <input type="text" class="form-control" id="Username" placeholder="Username" name="username">
  </div>
  <div class="form-group">
    <label for="Password">Password</label>
    <input type="password" class="form-control" id="Password" placeholder="Password" name="password">
  </div>
    <div class="pull-right"><button type="submit" class="btn btn-primary">Sign In</button></div>

</form>
</div>

</div>








<script type="text/javascript" src="https://code.jquery.com/jquery-2.1.1.min.js"></script>
        <script type="text/javascript" src="js/materialize.min.js"></script>

        <!-- Slider Javascript -->
        <script src='http://cdnjs.cloudflare.com/ajax/libs/jquery/2.1.3/jquery.min.js'></script>
        <script src="js/slider.js" type="text/javascript"></script>
</body>
{%  endblock %}

review_it/templates/write_review.html
{% extends 'base.html' %}

{% block content %}
    <body>

<nav class="navbar navbar-default">
    <div class="container-fluid">
    <div class="col-md-4">
     <div class="navbar-header">
       <a class="avbar-brand" href="#">
         <img alt="Brand" src="https://www.freelogoservices.com/api/main/images/1j+ojl1FOMkX9WypfBe43D6kj...GJqBBKkRbJwXs1M3EMoAJtlCcohfps...fw+" style="padding-top:-20px;height:65px;">
       </a>
     </div></div>
    <div class="col-md-6">

    <form class="navbar-form navbar-left" action="{% url 'review_it:search' %}" method="POST">
    {% csrf_token %}
        <div class="form-group">
          <input type="text" class="form-control" placeholder="Search" name="svalue">
        </div>
        <button type="submit" class="btn btn-default">Submit</button>
      </form>

    </div>
    <div class="col-md-2"><a href="{% url 'review_it:logout' %}" type="button" class="btn btn-default navbar-btn" style="margin-left:1em;">Sign Out</a></div>
    </div>
    </nav>




<div class="row">
<div class="col-md-2"><p></p></div>
<div class="col-md-8">
<h1 style="padding-left:8em;">Write Review</h1>
<form action="{% url 'review_it:add_review' %}" method="POST">
{% csrf_token %}
    <div class="row">
    <div class="col-md-6">
    <div class="form-group required">
    <label for="Title">Book/Movie Title</label>
    <input type="text" name="title" class="form-control" id="title" placeholder="Title" required="True">
    </div></div>
    <div class="col-md-6">
    <div class="form-group required">
    <label for="Author">Author</label>
    <input type="text" class="form-control" name="author" id="author" placeholder="Author" required="True">
    </div></div></div>
    <div class="row">
    <div class="col-md-6">
    <div class="form-group required">
    <label for="Publisher">Publisher</label>
    <input type="text" class="form-control" id="publisher" name="publisher" placeholder="Publisher" >
    </div></div>
    <div class="col-md-6">
    <div class="form-group">
    <label for="Rating">Rating</label><br>
    <label class="radio-inline">
     <input id="one" name="star_rating" value="1" type="radio" >
     1</label>
    <label class="radio-inline">
     <input id="two" name="star_rating" value="2" type="radio" >
     2</label>
    <label class="radio-inline">
     <input id="three" name="star_rating" value="3" type="radio">
     3</label>
    <label class="radio-inline">
     <input id="four" name="star_rating" value="4" type="radio">
     4</label>
    <label class="radio-inline">
     <input id="five" name="star_rating" value="5" type="radio">
     5</label>
    </div>
    </div></div>
    <div class="form-group required">
    <label for="Publisher">Review</label>
    <textarea type="text" class="form-control" id="review" name="review" placeholder="It's a.." rows="8" style="overflow:auto;"></textarea>
    </div>
    <div class="pull-right"><button type="submit" class="btn btn-primary">Submit</button></div>

</form>
</div>
</div>








<script type="text/javascript" src="https://code.jquery.com/jquery-2.1.1.min.js"></script>
        <script type="text/javascript" src="js/materialize.min.js"></script>

        <!-- Slider Javascript -->
        <script src='http://cdnjs.cloudflare.com/ajax/libs/jquery/2.1.3/jquery.min.js'></script>
        <script src="js/slider.js" type="text/javascript"></script>
</body>
{% endblock %}